<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountryLangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('country_langs')->insert([
            ['alias' => 'ad', 'name' => 'Andorra'],
            ['alias' => 'ae', 'name' => 'United Arab Emiratesм'],
            ['alias' => 'af', 'name' => 'Afghanistan'],
            ['alias' => 'ag', 'name' => 'Antigua and Barbuda'],
            ['alias' => 'ai', 'name' => 'Anguilla'],
            ['alias' => 'al', 'name' => 'Albania'],
            ['alias' => 'am', 'name' => 'Armenia'],
            ['alias' => 'ao', 'name' => 'Angola'],
            ['alias' => 'aq', 'name' => 'Antarctica'],
            ['alias' => 'ar', 'name' => 'Argentina'],
            ['alias' => 'as', 'name' => 'American Samoa'],
            ['alias' => 'at', 'name' => 'Austria'],
            ['alias' => 'au', 'name' => 'Australia'],
            ['alias' => 'aw', 'name' => 'Aruba'],
            ['alias' => 'ax', 'name' => 'Aland Islands'],
            ['alias' => 'az', 'name' => 'Azerbaijan'],
            ['alias' => 'ba', 'name' => 'Bosnia and Herzegowina'],
            ['alias' => 'bb', 'name' => 'Barbados'],
            ['alias' => 'bd', 'name' => 'Bangladesh'],
            ['alias' => 'be', 'name' => 'Belgium'],
            ['alias' => 'bf', 'name' => 'Burkina Faso'],
            ['alias' => 'bg', 'name' => 'Bulgaria'],
            ['alias' => 'bh', 'name' => 'Bahrain'],
            ['alias' => 'bi', 'name' => 'Burundi'],
            ['alias' => 'bj', 'name' => 'Benin'],
            ['alias' => 'bl', 'name' => 'Saint Barthélemy'],
            ['alias' => 'bm', 'name' => 'Bermuda'],
            ['alias' => 'bn', 'name' => 'Brunei Darussalam'],
            ['alias' => 'bo', 'name' => 'Bolivia'],
            ['alias' => 'bq', 'name' => 'Bonaire, Sint Eustatius and Saba'],
            ['alias' => 'br', 'name' => 'Brazil'],
            ['alias' => 'bs', 'name' => 'Bahamas'],
            ['alias' => 'bt', 'name' => 'Bhutan'],
            ['alias' => 'bv', 'name' => 'Bouvet Island'],
            ['alias' => 'bw', 'name' => 'Botswana'],
            ['alias' => 'by', 'name' => 'Belarus'],
            ['alias' => 'bz', 'name' => 'Belize'],
            ['alias' => 'ca', 'name' => 'Canada'],
            ['alias' => 'cc', 'name' => 'Cocos (Keeling) Islands'],
            ['alias' => 'cd', 'name' => 'Congo, Democratic Republic of the'],
            ['alias' => 'cf', 'name' => 'Central African Republic'],
            ['alias' => 'cg', 'name' => 'Congo'],
            ['alias' => 'ch', 'name' => 'Switzerland'],
            ['alias' => 'ci', 'name' => 'Cote D`Ivoire'],
            ['alias' => 'ck', 'name' => 'Cook Islands'],
            ['alias' => 'cl', 'name' => 'Chile'],
            ['alias' => 'cm', 'name' => 'Cameroon'],
            ['alias' => 'cn', 'name' => 'China'],
            ['alias' => 'co', 'name' => 'Colombia'],
            ['alias' => 'cr', 'name' => 'Costa Rica'],
            ['alias' => 'cu', 'name' => 'Cuba'],
            ['alias' => 'cv', 'name' => 'Cape Verde'],
            ['alias' => 'cw', 'name' => 'Curaçao'],
            ['alias' => 'cx', 'name' => 'Christmas Island'],
            ['alias' => 'cy', 'name' => 'Cyprus'],
            ['alias' => 'cz', 'name' => 'Czech Republic'],
            ['alias' => 'de', 'name' => 'Germany'],
            ['alias' => 'dj', 'name' => 'Djibouti'],
            ['alias' => 'dk', 'name' => 'Denmark'],
            ['alias' => 'dm', 'name' => 'Dominica'],
            ['alias' => 'do', 'name' => 'Dominican Republic'],
            ['alias' => 'dz', 'name' => 'Algeria'],
            ['alias' => 'ec', 'name' => 'Ecuador'],
            ['alias' => 'ee', 'name' => 'Estonia'],
            ['alias' => 'eg', 'name' => 'Egypt'],
            ['alias' => 'eh', 'name' => 'Western Sahara'],
            ['alias' => 'er', 'name' => 'Eritrea'],
            ['alias' => 'es', 'name' => 'Spain'],
            ['alias' => 'et', 'name' => 'Ethiopia'],
            ['alias' => 'fi', 'name' => 'Finland'],
            ['alias' => 'fj', 'name' => 'Fiji'],
            ['alias' => 'fk', 'name' => 'Falkland Islands (Malvinas)'],
            ['alias' => 'fm', 'name' => 'Micronesia, Federated States of'],
            ['alias' => 'fo', 'name' => 'Faroe Islands'],
            ['alias' => 'fr', 'name' => 'France'],
            ['alias' => 'ga', 'name' => 'Gabon'],
            ['alias' => 'gb', 'name' => 'United Kingdom'],
            ['alias' => 'gd', 'name' => 'Grenada'],
            ['alias' => 'ge', 'name' => 'Georgia'],
            ['alias' => 'gf', 'name' => 'French Guiana'],
            ['alias' => 'gg', 'name' => 'Guernsey'],
            ['alias' => 'gh', 'name' => 'Ghana'],
            ['alias' => 'gi', 'name' => 'Gibraltar'],
            ['alias' => 'gl', 'name' => 'Greenland'],
            ['alias' => 'gm', 'name' => 'Gambia'],
            ['alias' => 'gn', 'name' => 'Guinea'],
            ['alias' => 'gp', 'name' => 'Guadeloupe'],
            ['alias' => 'gq', 'name' => 'Equatorial Guinea'],
            ['alias' => 'gr', 'name' => 'Greece'],
            ['alias' => 'gs', 'name' => 'South Georgia and the South Sandwich Islands'],
            ['alias' => 'gt', 'name' => 'Guatemala'],
            ['alias' => 'gu', 'name' => 'Guam'],
            ['alias' => 'gw', 'name' => 'Guinea-bissau'],
            ['alias' => 'gy', 'name' => 'Guyana'],
            ['alias' => 'hk', 'name' => 'Hong Kong'],
            ['alias' => 'hm', 'name' => 'Heard and Mc Donald Islands'],
            ['alias' => 'hn', 'name' => 'Honduras'],
            ['alias' => 'hr', 'name' => 'Croatia'],
            ['alias' => 'ht', 'name' => 'Haiti'],
            ['alias' => 'hu', 'name' => 'Hungary'],
            ['alias' => 'id', 'name' => 'Indonesia'],
            ['alias' => 'ie', 'name' => 'Ireland'],
            ['alias' => 'il', 'name' => 'Israel'],
            ['alias' => 'im', 'name' => 'Isle of Man'],
            ['alias' => 'in', 'name' => 'India'],
            ['alias' => 'io', 'name' => 'British Indian Ocean Territory'],
            ['alias' => 'iq', 'name' => 'Iraq'],
            ['alias' => 'ir', 'name' => 'Iran (Islamic Republic of)'],
            ['alias' => 'is', 'name' => 'Iceland'],
            ['alias' => 'it', 'name' => 'Italy'],
            ['alias' => 'je', 'name' => 'Jersey'],
            ['alias' => 'jm', 'name' => 'Jamaica'],
            ['alias' => 'jo', 'name' => 'Jordan'],
            ['alias' => 'jp', 'name' => 'Japan'],
            ['alias' => 'ke', 'name' => 'Kenya'],
            ['alias' => 'kg', 'name' => 'Kyrgyzstan'],
            ['alias' => 'kh', 'name' => 'Cambodia'],
            ['alias' => 'ki', 'name' => 'Kiribati'],
            ['alias' => 'km', 'name' => 'Comoros'],
            ['alias' => 'kn', 'name' => 'Saint Kitts and Nevis'],
            ['alias' => 'kp', 'name' => 'Korea, Democratic People`s Republic of'],
            ['alias' => 'kr', 'name' => 'Korea, Republic of'],
            ['alias' => 'kw', 'name' => 'Kuwait'],
            ['alias' => 'ky', 'name' => 'Cayman Islands'],
            ['alias' => 'kz', 'name' => 'Kazakhstan'],
            ['alias' => 'la', 'name' => 'Lao People`s Democratic Republic'],
            ['alias' => 'lb', 'name' => 'Lebanon'],
            ['alias' => 'lc', 'name' => 'Saint Lucia'],
            ['alias' => 'li', 'name' => 'Liechtenstein'],
            ['alias' => 'lk', 'name' => 'Sri Lanka'],
            ['alias' => 'lr', 'name' => 'Liberia'],
            ['alias' => 'ls', 'name' => 'Lesotho'],
            ['alias' => 'lt', 'name' => 'Lithuania'],
            ['alias' => 'lu', 'name' => 'Luxembourg'],
            ['alias' => 'lv', 'name' => 'Latvia'],
            ['alias' => 'ly', 'name' => 'Libya'],
            ['alias' => 'ma', 'name' => 'Morocco'],
            ['alias' => 'mc', 'name' => 'Monaco'],
            ['alias' => 'md', 'name' => 'Moldova, Republic of'],
            ['alias' => 'me', 'name' => 'Montenegro'],
            ['alias' => 'mf', 'name' => 'Saint Martin (French part)'],
            ['alias' => 'mg', 'name' => 'Madagascar'],
            ['alias' => 'mh', 'name' => 'Marshall Islands'],
            ['alias' => 'mk', 'name' => 'Macedonia, The Former Yugoslav Republic of'],
            ['alias' => 'ml', 'name' => 'Mali'],
            ['alias' => 'mm', 'name' => 'Myanmar'],
            ['alias' => 'mn', 'name' => 'Mongolia'],
            ['alias' => 'mo', 'name' => 'Macao'],
            ['alias' => 'mp', 'name' => 'Northern Mariana Islands'],
            ['alias' => 'mq', 'name' => 'Martinique'],
            ['alias' => 'mr', 'name' => 'Mauritania'],
            ['alias' => 'ms', 'name' => 'Montserrat'],
            ['alias' => 'mt', 'name' => 'Malta'],
            ['alias' => 'mu', 'name' => 'Mauritius'],
            ['alias' => 'mv', 'name' => 'Maldives'],
            ['alias' => 'mw', 'name' => 'Malawi'],
            ['alias' => 'mx', 'name' => 'Mexico'],
            ['alias' => 'my', 'name' => 'Malaysia'],
            ['alias' => 'mz', 'name' => 'Mozambique'],
            ['alias' => 'na', 'name' => 'Namibia'],
            ['alias' => 'nc', 'name' => 'New Caledonia'],
            ['alias' => 'ne', 'name' => 'Niger'],
            ['alias' => 'nf', 'name' => 'Norfolk Island'],
            ['alias' => 'ng', 'name' => 'Nigeria'],
            ['alias' => 'ni', 'name' => 'Nicaragua'],
            ['alias' => 'nl', 'name' => 'Netherlands'],
            ['alias' => 'no', 'name' => 'Norway'],
            ['alias' => 'np', 'name' => 'Nepal'],
            ['alias' => 'nr', 'name' => 'Nauru'],
            ['alias' => 'nu', 'name' => 'Niue'],
            ['alias' => 'nz', 'name' => 'New Zealand'],
            ['alias' => 'om', 'name' => 'Oman'],
            ['alias' => 'pa', 'name' => 'Panama'],
            ['alias' => 'pe', 'name' => 'Peru'],
            ['alias' => 'pf', 'name' => 'French Polynesia'],
            ['alias' => 'pg', 'name' => 'Papua New Guinea'],
            ['alias' => 'ph', 'name' => 'Philippines'],
            ['alias' => 'pk', 'name' => 'Pakistan'],
            ['alias' => 'pl', 'name' => 'Poland'],
            ['alias' => 'pm', 'name' => 'St. Pierre and Miquelon'],
            ['alias' => 'pn', 'name' => 'Pitcairn'],
            ['alias' => 'pr', 'name' => 'Puerto Rico'],
            ['alias' => 'ps', 'name' => 'Palestine, State of'],
            ['alias' => 'pt', 'name' => 'Portugal'],
            ['alias' => 'pw', 'name' => 'Palau'],
            ['alias' => 'py', 'name' => 'Paraguay'],
            ['alias' => 'qa', 'name' => 'Qatar'],
            ['alias' => 're', 'name' => 'Reunion'],
            ['alias' => 'ro', 'name' => 'Romania'],
            ['alias' => 'rs', 'name' => 'Serbia'],
            ['alias' => 'ru', 'name' => 'Russian Federation'],
            ['alias' => 'rw', 'name' => 'Rwanda'],
            ['alias' => 'sa', 'name' => 'Saudi Arabia'],
            ['alias' => 'sb', 'name' => 'Solomon Islands'],
            ['alias' => 'sc', 'name' => 'Seychelles'],
            ['alias' => 'sd', 'name' => 'Sudan'],
            ['alias' => 'se', 'name' => 'Sweden'],
            ['alias' => 'sg', 'name' => 'Singapore'],
            ['alias' => 'sh', 'name' => 'Saint Helena'],
            ['alias' => 'si', 'name' => 'Slovenia'],
            ['alias' => 'sj', 'name' => 'Svalbard and Jan Mayen Islands'],
            ['alias' => 'sk', 'name' => 'Slovakia (Slovak Republic)'],
            ['alias' => 'sl', 'name' => 'Sierra Leone'],
            ['alias' => 'sm', 'name' => 'San Marino'],
            ['alias' => 'sn', 'name' => 'Senegal'],
            ['alias' => 'so', 'name' => 'Somalia'],
            ['alias' => 'sr', 'name' => 'Suriname'],
            ['alias' => 'ss', 'name' => 'South Sudan'],
            ['alias' => 'st', 'name' => 'Sao Tome and Principe'],
            ['alias' => 'sv', 'name' => 'El Salvador'],
            ['alias' => 'sx', 'name' => 'Sint Maarten (Dutch part)'],
            ['alias' => 'sy', 'name' => 'Syrian Arab Republic'],
            ['alias' => 'sz', 'name' => 'Eswatini'],
            ['alias' => 'tc', 'name' => 'Turks and Caicos Islands'],
            ['alias' => 'td', 'name' => 'Chad'],
            ['alias' => 'tf', 'name' => 'French Southern Territories'],
            ['alias' => 'tg', 'name' => 'Togo'],
            ['alias' => 'th', 'name' => 'Thailand'],
            ['alias' => 'tj', 'name' => 'Tajikistan'],
            ['alias' => 'tk', 'name' => 'Tokelau'],
            ['alias' => 'tl', 'name' => 'Timor-Leste'],
            ['alias' => 'tm', 'name' => 'Turkmenistan'],
            ['alias' => 'tn', 'name' => 'Tunisia'],
            ['alias' => 'to', 'name' => 'Tonga'],
            ['alias' => 'tr', 'name' => 'Turkey'],
            ['alias' => 'tt', 'name' => 'Trinidad and Tobago'],
            ['alias' => 'tv', 'name' => 'Tuvalu'],
            ['alias' => 'tw', 'name' => 'Taiwan'],
            ['alias' => 'tz', 'name' => 'Tanzania, United Republic of'],
            ['alias' => 'ua', 'name' => 'Ukraine'],
            ['alias' => 'ug', 'name' => 'Uganda'],
            ['alias' => 'um', 'name' => 'United States Minor Outlying Islands'],
            ['alias' => 'us', 'name' => 'United States'],
            ['alias' => 'uy', 'name' => 'Uruguay'],
            ['alias' => 'uz', 'name' => 'Uzbekistan'],
            ['alias' => 'va', 'name' => 'Holy See (Vatican City State)'],
            ['alias' => 'vc', 'name' => 'Saint Vincent and the Grenadines'],
            ['alias' => 've', 'name' => 'Venezuela'],
            ['alias' => 'vg', 'name' => 'Virgin Islands (British)'],
            ['alias' => 'vi', 'name' => 'Virgin Islands (U.S.)'],
            ['alias' => 'vn', 'name' => 'Viet Nam'],
            ['alias' => 'vu', 'name' => 'Vanuatu'],
            ['alias' => 'wf', 'name' => 'Wallis and Futuna Islands'],
            ['alias' => 'ws', 'name' => 'Samoa'],
            ['alias' => 'ye', 'name' => 'Yemen'],
            ['alias' => 'yt', 'name' => 'Mayotte'],
            ['alias' => 'za', 'name' => 'South Africa'],
            ['alias' => 'zm', 'name' => 'Zambia'],
            ['alias' => 'zw', 'name' => 'Zimbabwe'],
            ['alias' => 'yt', 'name' => 'Mayotte'],
            ['alias' => 'za', 'name' => 'South Africa'],
            ['alias' => 'zm', 'name' => 'Zambia'],
            ['alias' => 'zw', 'name' => 'Zimbabwe']
        ]);
    }
}
